# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labelgame', '0003_auto_20170823_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date photo was created.'),
        ),
    ]
